"""Minimal offline license check.

Not DRM — the goal is to gate the Pro code path for honest customers, the
same trust model most small indie CLI tools sold on Gumroad/itch use.
Key format: AGR-<16 hex chars>-<4 hex checksum>, checksum = first 4 hex
chars of sha256(secret + payload). Keys are generated by `make_key()` at
sale time (e.g. from a simple Gumroad webhook -> key generator), never
shipped with the free download.
"""

import hashlib
import os
import secrets as pysecrets

# In production this lives in a deploy secret, not in the repo. Placeholder
# here so the free/open-source version is fully runnable end to end.
_SIGNING_SECRET = os.environ.get("AGENTGUARD_SIGNING_SECRET", "dev-only-secret-change-me")


def _checksum(payload: str) -> str:
    return hashlib.sha256((_SIGNING_SECRET + payload).encode()).hexdigest()[:4]


def make_key() -> str:
    payload = pysecrets.token_hex(8)
    return f"AGR-{payload}-{_checksum(payload)}"


def is_valid(key: str | None) -> bool:
    if not key:
        return False
    parts = key.strip().split("-")
    if len(parts) != 3 or parts[0] != "AGR":
        return False
    payload, checksum = parts[1], parts[2]
    if len(payload) != 16 or len(checksum) != 4:
        return False
    return _checksum(payload) == checksum
